### ISSUE TITLE
PID overshoots and oscillates

### ISSUE THREAD

**Issue by stunt822** [stunt822/SteadyPass#2]
Under some circumbstatces - control will overshoot and oscillate speed.  For example when speed is below target - throttle increase may be too slow, so speed is dropping further.  Leading to slow oscillations over 5-10 second period.

**Comment by CRaShCoUrSe316** [comment]
* Original calculation by MPH has been removed and replaced with PID Calculation
* PID Needs testing/calibration and further adjustments on the water.


!* RPM mode needs to be replaced

**Comment by CRaShCoUrSe316** [comment]
*Combined RPM and speed mode with a single function that changes the input when the mode is changed.
*Removed previous calculation style.
*Two modes of calculation available and set by an EPPROM reading (read EEPROM(19) for a 1 to set adaptive tuning mode, is not ==1 then Proportion on Measure mode is set by default.

**Comment by CRaShCoUrSe316** [comment]
TODO
* integrate mode change into menu option
*integrate calc type into menu option
*enhancement- add knob turn setting to adjust the aggressiveness of the PID calculation for a harder/softer launch

**Comment by CRaShCoUrSe316** [comment]
New PID functioning, Needs testing and adjustments on Kp,Ki,Kd settings

**Comment by CRaShCoUrSe316** [comment]
New PID has been water tested on initial No pull at 11.5 mph. At best, held a range of 11-12 mph. some outbreaks to wider range during testing. Settings need to be dialed in much better to properly gauge accuracy. More testing needed to see if issue is resolved with new PID calculations.

**Comment by CRaShCoUrSe316** [comment]
Target speed holding perfectly with current setting. Overshoot still needs to be fixed.
