### ISSUE TITLE
set default servo values - 950 and 1950

### ISSUE THREAD

**Issue by stunt822** [stunt822/SteadyPass#57]
turns out all the linear servos we use now have same setting.
please set default to 950 on low and 1950 on high.

**Comment by CRaShCoUrSe316** [comment]
Need to set this in the initializer

**Comment by CRaShCoUrSe316** [comment]
Set defaults and limits to 950 and 1950 for both menus.. need to test

**Comment by CRaShCoUrSe316** [comment]
working
